# Generated by Django 4.1 on 2022-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
